language: generic  

sudo: required

services:
  - docker

before_install:
  - docker build -t mugeesh/frontend_react_pro -f Dockerfile.dev .

script:
  - docker run -e CI=true mugeesh/frontend_react_pro npm run test -- --watchAll=false
  #- docker run mugeesh/frontend_react_pro npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "fronted_web_react_docker"
  env: "FrontedWebReactDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-284249289744"
  bucket_path: "fronted_web_react_docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
