version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app  # from development real time update for developement purpose 
  
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev 
    volumes:
      - /app/node_modules
      - .:/app  # from development real time update for developement purpose 
    command: ["npm","run","test"]


#$docker build -t mugeesh/frontend_react_pro -f Dockerfile.dev .
#$ docker run mugeesh/frontend_react_pro npm run test -- --coverage